<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

<parent>
	<groupId>d276675b-c310-4c9c-adf3-3f8ee2940a57</groupId>
	<artifactId>master-bom</artifactId>
	<version>1.0.0</version>
	<relativePath>../master-bom/pom.xml</relativePath>
</parent>

	<groupId>d276675b-c310-4c9c-adf3-3f8ee2940a57</groupId>
	<artifactId>parent-pom</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>

	<name>parent-pom</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<app.runtime>4.9.1</app.runtime>
		<mule.maven.plugin.version>4.3.0</mule.maven.plugin.version>
	</properties>

    <!-- Se eliminan todas las versiones, quedan administradas por el master-bom -->

	<build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <configuration>
                        <resources>
                            <resource>
                                <directory>src/main/resources</directory>
                                <filtering>false</filtering>
                            </resource>
                            <resource>
                                <directory>src/main/resources</directory>
                                <filtering>true</filtering>
                                <includes>
                                    <include>properties.yaml</include>
                                </includes>
                            </resource>
                        </resources>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.mule.tools.maven</groupId>
                    <artifactId>mule-maven-plugin</artifactId>
                    <extensions>true</extensions>
                </plugin>
            </plugins>
        </pluginManagement>
	</build>

    <!-- Se eliminan todas las dependencias, resources y pluginRepositories, estan quedan en el master-bom -->

</project>
